CREATE TABLESPACE VNTS_TBSP
ADD DATAFILE 'vnts-dtfl'
ENGINE = NDB;
ALTER TABLE USER TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE USER_REGISTRY TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE USR_ATTACH TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE LANG TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE SETTING_USER TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE COUNTRY TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE CATEGORY_REVIEW_MAIN TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE CATEGORY_REVIEW TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE GEO_SITE TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE SITE TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE REVIEW TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE REVIEW_ATTACH TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE CITY TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE CITY_REVIEW TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE CITY_REV_ATT TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE REVIEW_CITY_REVIEW TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE COUNTRY_REVIEW TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE COUNTRY_REV_ATT TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE CITY_REV_COUNTRY_REV TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE MESSAGE TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE MSG_DEN TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE REQUEST TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE REVIEW_STAR TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE CITY_REV_STAR TABLESPACE VNTS_TBSP CHARACTER SET utf8;
ALTER TABLE COUNTRY_REV_STAR TABLESPACE VNTS_TBSP CHARACTER SET utf8;