DROP TABLE REQUEST;
DROP TABLE MSG_DEN;
DROP TABLE MESSAGE;
DROP TABLE SETTING_USER;

DROP TABLE REVIEW_STAR;
DROP TABLE REVIEW_ATTACH;
DROP TABLE REVIEW_CITY_REVIEW;
DROP TABLE REVIEW;
DROP TABLE SITE;
DROP TABLE GEO_SITE;
DROP TABLE CATEGORY_REVIEW;
DROP TABLE CATEGORY_REVIEW_MAIN;

DROP TABLE CITY_REV_STAR;
DROP TABLE CITY_REV_COUNTRY_REV;
DROP TABLE CITY_REV_ATT;
DROP TABLE CITY_REVIEW ;
DROP TABLE CITY;

DROP TABLE COUNTRY_REV_STAR;
DROP TABLE COUNTRY_REV_ATT;
DROP TABLE COUNTRY_REVIEW;

DROP TABLE COUNTRY;
DROP TABLE LANG;

DROP TABLE USR_ATTACH;
DROP TABLE USER_REGISTRY;
DROP TABLE USER;